### ISSUE TITLE
Windows OSError: screen grab failed

### ISSUE THREAD

**Issue by peratik** [bitrate16/httprd#1]
Hi,

OS Windows Server 2019 Standard
Python 3.11.5

Error:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\httprd\httprd.py", line 274, in async_worker
    image = PIL.ImageGrab.grab()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\httprd\env\Lib\site-packages\PIL\ImageGrab.py", line 47, in grab
    offset, size, data = Image.core.grabscreen_win32(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: screen grab failed
```

Please advise.

**Comment by bitrate16** [comment]
@peratik 
May be related to https://stackoverflow.com/a/61151739
