### ISSUE TITLE
Is there a way to launch httprd via ssh ?

### ISSUE THREAD

**Issue by ludetie** [bitrate16/httprd#2]
Hello,
Is there a way to launch httprd via ssh ?
When I launch httprd via ssh :
python3 httprd.py --help
the answer is :
Traceback (most recent call last):
  File "httprd.py", line 29, in <module>
    import pyautogui
  File "/home/ludeti/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/home/ludeti/.local/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None

**Comment by ludetie** [comment]
Hello,
I found ; once connected to ssh :
export DISPLAY=:0.0 && python3 httprd.py --help

httprd is great, thank you !

**Comment by bitrate16** [comment]
> export DISPLAY=:0.0

Yes, you have to tell ssh tty which X11/Wayland session display to use because in common DISPLAY is exported only in TTY's created under GUI environment (like terninal, etc)
